version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - calculations/target/calculations-0.0.1-SNAPSHOT.jar
    - calculationIU/target/calculationIU-0.0.1-SNAPSHOT.jar
    - calculationCircuitbreaker/target/calculationCircuitbreaker-0.0.1-SNAPSHOT.jar